#!/usr/bin/env python3
"""Generate tb/asm/bench_insn.s: cycles per instruction form.

Each form runs as 8 copies x 100 passes between two STAMPs (user mode,
copyback data at BUF through DTT0; the TRAP #2 handler writes the stamp).
A form may need a setup line before each pass (e.g. reloading a pointer).
The bench prints cycles and instructions per stamp; parse with
tb/tools/bench_insn_report.py."""
import sys
FORMS = [
    # name, body (one copy), setup per pass
    ("moveq", "moveq #1,d2", ""),
    ("move.l Dn,Dn", "move.l d1,d2", ""),
    ("add.l Dn,Dn", "add.l d1,d2", ""),
    ("addq.l", "addq.l #1,d2", ""),
    ("addi.l #imm", "addi.l #$12345,d2", ""),
    ("cmp.l+bne(nt)+moveq", "cmp.l d1,d1\n\tbne.s *+4\n\tmoveq #0,d5", ""),
    ("bra.s taken over moveq", "bra.s *+4\n\tmoveq #0,d5", ""),
    ("lsl.l #3", "lsl.l #3,d2", ""),
    ("asr.l Dn", "asr.l d3,d2", ""),
    ("rol.w #4", "rol.w #4,d2", ""),
    ("roxl.l #1", "roxl.l #1,d2", ""),
    ("swap", "swap d2", ""),
    ("ext.l", "ext.l d2", ""),
    ("neg.l", "neg.l d2", ""),
    ("not.l", "not.l d2", ""),
    ("clr.l Dn", "clr.l d2", ""),
    ("exg", "exg d1,d2", ""),
    ("scc", "seq d2", ""),
    ("mulu.w", "mulu.w d1,d2", ""),
    ("muls.l", "muls.l d1,d2", ""),
    ("divu.w", "divu.w d4,d5", "move.l #1000,d5"),
    ("divs.l", "divs.l d4,d5", "move.l #100000,d5"),
    ("move.l (An),Dn", "move.l (a0),d2", ""),
    ("move.l Dn,(An)", "move.l d2,(a0)", ""),
    ("move.l d16(An),Dn", "move.l 4(a0),d2", ""),
    ("move.l (d8,An,Xn),Dn", "move.l (4,a0,d6.l),d2", ""),
    ("move.l (An)+,Dn", "move.l (a0)+,d2", "lea (BUF).l,a0"),
    ("move.l Dn,-(An)", "move.l d2,-(a1)", "lea (BUF+64).l,a1"),
    ("move.l (An),(An)", "move.l (a0),(a2)", ""),
    ("add.l (An),Dn", "add.l (a0),d2", ""),
    ("add.l Dn,(An)", "add.l d2,(a0)", ""),
    ("addq.l #1,(An)", "addq.l #1,(a0)", ""),
    ("tst.l (An)", "tst.l (a0)", ""),
    ("clr.l (An)", "clr.l (a0)", ""),
    ("move.l abs.l,Dn", "move.l (BUF).l,d2", ""),
    ("lea d16(An)", "lea 4(a0),a3", ""),
    ("lea (d8,An,Xn)", "lea (4,a0,d6.l),a3", ""),
    ("move.l Dn,An", "move.l d1,a3", ""),
    ("move+use as base", "move.l a0,a3\n\tmove.l (a3),d2", ""),
    ("load+use as base", "move.l (a4),a3\n\tmove.l (a3),d2", ""),
    ("add+use as index", "move.l d6,d5\n\tadd.l d1,d5\n\tmove.l (a0,d5.l*4),d2", ""),
    ("lsl+and+use as index", "move.w d4,d5\n\tlsl.w #2,d5\n\tand.l #$FFFF,d5\n\tmove.l (a0,d5.l),d2", ""),
    ("push+pop", "move.l d2,-(sp)\n\tmove.l (sp)+,d2", ""),
    ("bsr+rts", "bsr.s *+4\n\tbra.s *+4\n\trts", ""),
    ("link+unlk", "link a5,#-8\n\tunlk a5", ""),
    ("movem.l 4 regs ->(An)", "movem.l d1/d2/d4/d5,(a0)", ""),
    ("movem.l (An),4 regs", "movem.l (a0),d1/d2/d4/d5", "moveq #1,d1\n\tmoveq #2,d4"),
    ("bfextu Dn", "bfextu d2{4:8},d5", ""),
    ("bfextu (An)", "bfextu (a0){4:8},d5", ""),
    ("bfins (An)", "bfins d5,(a0){4:8}", ""),
    ("bfffo Dn", "bfffo d2{0:32},d5", ""),
    ("abcd", "abcd d1,d2", ""),
    ("chk.w (no trap)", "chk.w d4,d1", ""),
    ("cas.l", "cas.l d2,d2,(a0)", ""),
    ("tas (An)", "tas (a0)", ""),
    ("move.l (An),Dn misal", "move.l 1(a0),d2", ""),
    ("move.l (An),Dn split", "move.l 14(a0),d2", ""),
    ("move.w (An),Dn split", "move.w 15(a0),d2", ""),
    ("move.l Dn,(An) split", "move.l d2,14(a0)", ""),
    ("move16", "move16 (a0)+,(a1)+", "lea (BUF).l,a0\n\tlea (BUF+$400).l,a1"),
    ("fmove.x FPm,FPn", "fmove.x fp0,fp6", ""),
    ("fadd.x FPm,FPn", "fadd.x fp0,fp1", ""),
    ("fmul.x FPm,FPn", "fmul.x fp0,fp2", ""),
    ("fmove.d (An),FPn", "fmove.d (a6),fp3", ""),
    ("fadd.d (An),FPn", "fadd.d (a6),fp4", ""),
    ("fmove.x (An),FPn", "fmove.x (16,a6),fp3", ""),
    ("fadd.x (An),FPn", "fadd.x (16,a6),fp4", ""),
    ("fmove.d FPn,(An)", "fmove.d fp1,(a2)", ""),
    ("fmove.s FPn,(An)", "fmove.s fp1,(a2)", ""),
    ("fmove.l FPn,Dn", "fmove.l fp1,d5", ""),
    ("fmove.l Dn,FPn", "fmove.l d1,fp5", ""),
]

def main(path):
    o = []
    w = o.append
    w("; generated by tb/tools/gen_bench_insn.py -- cycles per instruction form")
    w("STAMP\tequ\t$F108\nDONEREG\tequ\t$F102\nBUF\tequ\t$9800")
    w("stamp\tmacro\n\tmove.w\t#\\1,d7\n\ttrap\t#2\n\tendm")
    w("\torg\t0\n\tdc.l\t$3400\n\tdc.l\tstart\n\trept\t32\n\tdc.l\t0\n\tendr")
    w("\tdc.l\th_stamp\n\tdc.l\th_done\n\torg\t$400")
    w("start:\n\tmove.l\t#$0000A040,d0\n\tmovec\td0,dtt1\n\tmove.l\t#$00008020,d0\n\tmovec\td0,dtt0")
    w("\tmove.l\t#$80008000,d0\n\tmovec\td0,cacr\n\tlea\t($3000).l,a1\n\tmove\ta1,usp\n\tmove.w\t#$0000,sr")
    w("\tlea\t(BUF).l,a0\n\tlea\t(BUF+$100).l,a2\n\tlea\t(BUF+$200).l,a4\n\tmove.l\ta0,(a4)")
    w("\tmoveq\t#1,d1\n\tmoveq\t#2,d3\n\tmoveq\t#7,d4\n\tmoveq\t#8,d6\n\tmoveq\t#5,d2")
    w("\tlea\t(BUF+$40).l,a1")
    # FP registers hold ordinary numbers (after reset they read as NaN,
    # which takes the FPU's short special-operand path); a double at BUF
    w("\tfmove.l\t#3,fp0\n\tfmove.l\t#5,fp1\n\tfmove.l\t#7,fp2\n\tfmove.l\t#11,fp3")
    w("\tfmove.l\t#13,fp4\n\tfmove.l\t#17,fp5\n\tfmove.l\t#19,fp6")
    w("\tlea\t(BUF+$300).l,a6\n\tfmove.d\tfp0,(a6)\t; 3.0: the FP memory forms' operand\n\tfmove.x\tfp0,(16,a6)")
    for i, (name, body, setup) in enumerate(FORMS):
        w("; %d: %s" % (i + 1, name))
        w("\tstamp\t%d" % (2 * i + 1))
        w("\tmove.w\t#99,d0")
        w(".l%d:" % i)
        if setup:
            w("\t" + setup)
        for _ in range(8):
            w("\t" + body)
        w("\tdbra\td0,.l%d" % i)
        w("\tstamp\t%d" % (2 * i + 2))
    w("\ttrap\t#3")
    w("h_stamp:\n\tmove.w\td7,(STAMP).l\n\trte")
    w("h_done:\n\tmove.w\t#$600D,(DONEREG).l\n\tbra.s\t*")
    open(path, "w").write("\n".join(o) + "\n")

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "tb/asm/bench_insn.s")
