#!/usr/bin/env python3
"""Replay WinUAE cputest 68040 corpus slices on the AP68040-60 core.

  ./run_cputest.py CORPUS                     smoke set (one slice per group)
  ./run_cputest.py CORPUS --full              every slice
  ./run_cputest.py CORPUS --full --group AE --instruction 'Bcc.*'
  ./run_cputest.py CORPUS --full --group Basic --slice 0001 --round-limit 500

CORPUS is the v24 data040.zip, or its extracted data040/ directory.  Jobs are
generated by tools/cputest/replay_gen.py (APR2), run by tb_cputest.sv
(build_cputest.sh), one simulator process per slice, in parallel.
"""

import argparse
import concurrent.futures
import fnmatch
import gzip
import hashlib
import json
import os
import struct
import subprocess
import sys
import threading
import time
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
sys.path.insert(0, str(REPO / "tools" / "cputest"))
from replay_gen import generate  # noqa: E402

SIM = Path(os.environ.get("CPUTEST_SIM", REPO / "obj" / "obj_cputest" / "tb_cputest"))
MON = HERE / "build" / "cputest_mon.bin"

GROUPS = {
    "4_AE": "AE", "4_BASIC": "Basic", "4_Default": "Default",
    "4_EXTDST": "FFEXT_DST", "4_EXTSRC": "FFEXT_SRC", "4_FBASIC": "BasicFPU",
    "4_FINT": "intFPU", "4_FPACK": "PackedFPU", "4_IRQ": "IRQ",
    "4_ODDEXC": "ODD_EXC", "4_ODDIRQ": "ODD_IRQ", "4_ODDSTK": "ODD_STK",
}
SMOKE = [("Default", "DIVS.W", "0001"), ("Basic", "ABCD.B", "0001"),
         ("IRQ", "NOP", "0001"), ("AE", "BSR.B", "0001"),
         ("ODD_EXC", "ANDSR.W", "0001")]


def corpus_root(src: Path, work: Path) -> Path:
    if src.is_file():
        dest = work / "corpus"
        stamp = dest / ".src"
        ident = "%s %d" % (src.resolve(), src.stat().st_mtime_ns)
        if not stamp.exists() or stamp.read_text() != ident:
            dest.mkdir(parents=True, exist_ok=True)
            with zipfile.ZipFile(src) as zf:
                zf.extractall(dest)
            stamp.write_text(ident)
        src = dest
    for cand in (src, src / "data040", src / "data"):
        if any(cand.glob("4_*")):
            return cand
    raise SystemExit("no 4_* groups under %s" % src)


def unpack_daz(daz: Path, cache: Path) -> Path:
    key = hashlib.sha256(daz.read_bytes()).hexdigest()[:16]
    target = cache / key
    if (target / ".complete").exists():
        return target
    data = daz.read_bytes()
    target.mkdir(parents=True, exist_ok=True)
    off = index = 0
    while off + 8 <= len(data) and data[off:off + 4] == b"\xafMRG":
        length = struct.unpack(">I", data[off + 4:off + 8])[0]
        if length == 0:
            break
        (target / ("%04d.dat" % index)).write_bytes(
            gzip.decompress(data[off + 8:off + 8 + length]))
        off += 8 + length
        index += 1
    (target / ".complete").write_text(str(index))
    return target


def image(group_dir: Path, name: str, cache: Path) -> Path:
    gz = group_dir / (name + ".gz")
    src = gz if gz.exists() else group_dir / name
    key = hashlib.sha256(src.read_bytes()).hexdigest()[:16]
    out = cache / (name + "." + key)
    if not out.exists():
        # parallel slices share the cache: publish the file atomically
        cache.mkdir(parents=True, exist_ok=True)
        data = gzip.open(src).read() if src.suffix == ".gz" else src.read_bytes()
        tmp = out.with_name(out.name + ".%d.%d" % (os.getpid(), threading.get_ident()))
        tmp.write_bytes(data)
        os.replace(tmp, out)
    return out


def match(v, pats):
    return not pats or any(fnmatch.fnmatchcase(v, p) for p in pats)


def discover(root: Path, args):
    out = []
    for daz in sorted(root.glob("4_*/*/0000.daz")):
        group = GROUPS.get(daz.parent.parent.name, daz.parent.parent.name)
        instr = daz.parent.name
        if not match(group, args.group) or not match(instr, args.instruction):
            continue
        d = unpack_daz(daz, args.work / "unpacked")
        for dat in sorted(d.glob("[0-9][0-9][0-9][0-9].dat")):
            num = dat.name[:4]
            if num == "0000" or not match(num, args.slice):
                continue
            if not args.full and (group, instr, num) not in SMOKE:
                continue
            out.append(dict(group=group, instr=instr, slice=num, header=d / "0000.dat",
                            data=dat, gdir=daz.parent.parent))
    return out


def run(item, args):
    name = "%s--%s--%s" % (item["group"], item["instr"].replace("/", "_"), item["slice"])
    job = args.work / "jobs" / (name + ".apr2")
    log = args.work / "logs" / (name + ".log")
    job.parent.mkdir(parents=True, exist_ok=True)
    log.parent.mkdir(parents=True, exist_ok=True)
    t0 = time.monotonic()
    try:
        generate(str(item["header"]), str(item["data"]), str(job), args.round_limit)
        cmd = [str(SIM), "+job=%s" % job, "+mon=%s" % MON,
               "+lmem=%s" % image(item["gdir"], "lmem.dat", args.work / "images"),
               "+tmem=%s" % image(item["gdir"], "tmem.dat", args.work / "images")]
        cmd += args.plusarg
        p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                           text=True, timeout=args.timeout)
        out = p.stdout
        status = "pass" if "ALL TESTS PASSED" in out else "fail"
    except subprocess.TimeoutExpired as e:
        out = (e.stdout or b"").decode() if isinstance(e.stdout, bytes) else (e.stdout or "")
        status = "timeout"
    except Exception as e:  # report and continue with the other slices
        out = repr(e)
        status = "error"
    log.write_text(out)
    if not args.keep_jobs and job.exists():
        job.unlink()
    summ = [l for l in out.splitlines() if l.startswith("cputest replay")]
    first = [l for l in out.splitlines() if l.startswith(("MISMATCH", "FAIL"))][:1]
    return dict(name=name, status=status, seconds=time.monotonic() - t0,
                summary=summ[0] if summ else "", first=first[0] if first else "")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("corpus", type=Path)
    ap.add_argument("--work", type=Path, default=REPO / "obj" / "cputest")
    ap.add_argument("--full", action="store_true")
    ap.add_argument("--group", action="append", default=[])
    ap.add_argument("--instruction", action="append", default=[])
    ap.add_argument("--slice", action="append", default=[])
    ap.add_argument("--round-limit", type=int, default=None)
    ap.add_argument("--jobs", type=int, default=max(1, (os.cpu_count() or 2) // 2))
    ap.add_argument("--timeout", type=int, default=3600)
    ap.add_argument("--keep-jobs", action="store_true")
    ap.add_argument("--plusarg", action="append", default=[])
    args = ap.parse_args()
    args.work.mkdir(parents=True, exist_ok=True)
    if not SIM.exists() or not MON.exists():
        raise SystemExit("build the bench first: tb/build_cputest.sh")
    root = corpus_root(args.corpus, args.work)
    items = discover(root, args)
    print("%d slices" % len(items), flush=True)
    results = []
    with concurrent.futures.ThreadPoolExecutor(args.jobs) as ex:
        for r in ex.map(lambda it: run(it, args), items):
            results.append(r)
            print("%-6s %-44s %s %s" % (r["status"].upper(), r["name"], r["summary"],
                                        ("| " + r["first"]) if r["status"] != "pass" else ""),
                  flush=True)
    npass = sum(r["status"] == "pass" for r in results)
    print("PASSED %d / %d slices" % (npass, len(results)))
    (args.work / "summary.json").write_text(json.dumps(results, indent=1))
    sys.exit(0 if npass == len(results) else 1)


if __name__ == "__main__":
    main()
